//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSBEntities : DbContext
    {
        public SSBEntities()
            : base("name=SSBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackAir> BackAirs { get; set; }
        public virtual DbSet<BThrow> BThrows { get; set; }
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<DashAttack> DashAttacks { get; set; }
        public virtual DbSet<DashGrab> DashGrabs { get; set; }
        public virtual DbSet<DownAir> DownAirs { get; set; }
        public virtual DbSet<DownB> DownBs { get; set; }
        public virtual DbSet<DownSmash> DownSmashes { get; set; }
        public virtual DbSet<DThrow> DThrows { get; set; }
        public virtual DbSet<DTilt> DTilts { get; set; }
        public virtual DbSet<ForwardAir> ForwardAirs { get; set; }
        public virtual DbSet<FSmash> FSmashes { get; set; }
        public virtual DbSet<FThrow> FThrows { get; set; }
        public virtual DbSet<FTilt> FTilts { get; set; }
        public virtual DbSet<Grab> Grabs { get; set; }
        public virtual DbSet<NeutralAir> NeutralAirs { get; set; }
        public virtual DbSet<NeutralB> NeutralBs { get; set; }
        public virtual DbSet<PivotGrab> PivotGrabs { get; set; }
        public virtual DbSet<Pummel> Pummels { get; set; }
        public virtual DbSet<SideB> SideBs { get; set; }
        public virtual DbSet<UpAir> UpAirs { get; set; }
        public virtual DbSet<UpB> UpBs { get; set; }
        public virtual DbSet<UpSmash> UpSmashes { get; set; }
        public virtual DbSet<UThrow> UThrows { get; set; }
        public virtual DbSet<UTilt> UTilts { get; set; }
    }
}
